### ISSUE TITLE
UI Tweaks 1: Colors

### ISSUE THREAD

**Issue by austin-garrard** [translation-cards/txc-maker#44]
Per meeting with Olly 8/19

- [x] Top header/navbar should be #01579B
- [x] Bottom header on Deck Preview Screen should be #00447A
- [x] Publish button on Deck Preview Screen should be  #43A047  
- [x] Selected tab indicator should be white
- [x] Icons on cards should be 50% opacity

**Comment by DeuceTheCoder** [comment]
Colors checked, looks good!
